Que 1-Create a numpy array starting from 2 till 50 with a stepsize of 3

In [3]:
import numpy as np
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Que 2-Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
lst1=[22,89,45,34,12]
lst2=[4,8,36,25,77]
x=np.array(lst1)
y=np.array(lst2)
x

array([22, 89, 45, 34, 12])

In [5]:
y

array([ 4,  8, 36, 25, 77])

In [11]:
z=np.concatenate((x,y))
z

array([22, 89, 45, 34, 12,  4,  8, 36, 25, 77])

In [12]:
a=np.sort(z)
a

array([ 4,  8, 12, 22, 25, 34, 36, 45, 77, 89])

Que 3- Write a code snippet to find the dimensions of a ndarray and its size.

In [16]:
ar=np.ndarray([3,3,2])
ar

array([[[3.71711919e-316, 5.33590898e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78019354e-306, 1.15998412e-028]],

       [[2.44171989e+232, 8.00801729e+159],
        [1.30283744e-057, 6.35226581e-067],
        [1.89240870e-052, 1.30863175e-047]],

       [[1.03699111e-042, 5.79961775e+294],
        [1.43267083e+161, 4.56317366e-144],
        [4.82412328e+228, 1.04718130e-142]]])

In [19]:
print("Dimention of array=",np.ndim(ar))
print("size of array=",np.size(ar))

Dimention of array= 3
size of array= 18


Que 4-How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [26]:
a=np.arange(5)
a.shape

(5,)

In [27]:
row_vec = a[np.newaxis, :] 
row_vec.shape

(1, 5)

In [28]:
row_vec

array([[0, 1, 2, 3, 4]])

In [29]:
col_vec = a[:, np.newaxis]     
col_vec.shape

(5, 1)

In [30]:
col_vec

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
print("using np.expand-dims")
b = np.expand_dims(a, axis=(1,-2,3))
b.shape

using np.expand-dims


(5, 1, 1, 1)

Que 5- Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [24]:
arr=np.array([3,6,9,4])
arry=np.array([8,5,78,69])
print("Vertical Arrange:=\n",np.vstack((arr,arry)))
print("\t")
print("Horizantal Arrange:=",np.hstack((arr,arry)))

Vertical Arrange:=
 [[ 3  6  9  4]
 [ 8  5 78 69]]
	
Horizantal Arrange:= [ 3  6  9  4  8  5 78 69]


Que 6-How to get unique items and counts of unique items?

In [25]:
a = np.array( [44,78,44,56,12,78,44,10,10,44,23,55,23] )
print("Original array:")
print(a ,"\n")
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[44 78 44 56 12 78 44 10 10 44 23 55 23] 

Frequency of unique values of the said array:
[[10 12 23 44 55 56 78]
 [ 2  1  2  4  1  1  2]]
